kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user
subjects:
- kind: User
  name: aksdev@yradaks.onmicrosoft.com
